# Generated by deploy/homebrew/render-cask.sh in embeddedci-com/emi-analyzer on release.
# Edit it there, not here: the next release overwrites this file.
cask "emi-analyzer" do
  arch arm: "aarch64", intel: "x64"

  version "0.3.0"
  sha256 arm:   "0556e151400dfd74ae669b17ccb21735a5396c5d89b750ed9f65cfc3c51d415c",
         intel: "4b769198342637bcdd81abaecc03baba65288ce36daaa139b35b7148c2f5e0d8"

  url "https://github.com/embeddedci-com/emi-analyzer/releases/download/v#{version}/EMI.Analyzer_#{version}_#{arch}.dmg"
  name "EMI Analyzer"
  desc "Checks PCB layouts for the causes of EMI and EMC failures, on your own computer"
  homepage "https://github.com/embeddedci-com/emi-analyzer"

  livecheck do
    skip "Updated on release."
  end

  depends_on :macos

  app "EMI Analyzer.app"

  # Not code-signed yet: without this, macOS refuses to open the app.
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "{{appdir}}/EMI Analyzer.app"],
        must_succeed: false
  end

  zap trash: [
    "~/Library/Application Support/com.embeddedci.emi-analyzer",
    "~/Library/Application Support/emi-analyzer",
    "~/Library/Caches/com.embeddedci.emi-analyzer",
    "~/Library/WebKit/com.embeddedci.emi-analyzer",
  ]

  caveats <<~EOS
    EMI Analyzer runs its analysis in Docker. If you do not have Docker yet:
      brew install --cask docker-desktop
    or OrbStack:
      brew install --cask orbstack
  EOS
end
